name: .NET

env:
  GITHUB_ACTIONS: true
  XUNIT_ENVIRONMENT: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Display dotnet version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore Snebur.NET.slnx

    - name: Build
      run: dotnet build Snebur.NET.slnx --no-restore

    - name: Create lang folder
      run: mkdir -p ./Snebur.NET/lang
    - name: Test
      run: dotnet test Snebur.NET.slnx --verbosity normal --filter Category!=SkipGithubActions
    